title: Eric Gregory
show_downloads: false
author: Eric Gregory
url: "https://mrericsir.github.io"
baseurl: "/resume"
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
image: "/gorillas.bas.png"
social:
  name: Eric Gregory
  links:
    - https://github.com/MrEricSir/
    - https://www.linkedin.com/in/eric-p-gregory/
